// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebClinicAPI.Data;

namespace WebClinicAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191210215646_Visits")]
    partial class Visits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("WebClinicAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhysicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysicianId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PatientId = 6,
                            PhysicianId = 1,
                            Time = new DateTime(2019, 11, 29, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            PatientId = 6,
                            PhysicianId = 2,
                            Time = new DateTime(2019, 12, 2, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            PatientId = 6,
                            PhysicianId = 3,
                            Time = new DateTime(2019, 12, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            PatientId = 6,
                            PhysicianId = 2,
                            Time = new DateTime(2019, 11, 27, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        });
                });

            modelBuilder.Entity("WebClinicAPI.Models.Users.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AppUser");
                });

            modelBuilder.Entity("WebClinicAPI.Models.Users.Patient", b =>
                {
                    b.HasBaseType("WebClinicAPI.Models.Users.AppUser");

                    b.Property<string>("IllnessHistory")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedDrugs")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Patient");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1979, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patient1@gmail.com",
                            FirstName = "Geralt",
                            LastName = "Z Rivii",
                            Password = "10/w7o2juYBrGMh32/KbveULW9jk2tejpyUAD+uC6PE=",
                            Role = "Patient",
                            Sex = 0
                        });
                });

            modelBuilder.Entity("WebClinicAPI.Models.Users.Physician", b =>
                {
                    b.HasBaseType("WebClinicAPI.Models.Users.AppUser");

                    b.Property<int>("Specialization")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Physician");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1970, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "physician1@gmail.com",
                            FirstName = "Nathan",
                            LastName = "Drake",
                            Password = "10/w7o2juYBrGMh32/KbveULW9jk2tejpyUAD+uC6PE=",
                            Role = "Physician",
                            Sex = 0,
                            Specialization = 5
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1975, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "physician2@gmail.com",
                            FirstName = "Elena",
                            LastName = "Fisher",
                            Password = "10/w7o2juYBrGMh32/KbveULW9jk2tejpyUAD+uC6PE=",
                            Role = "Physician",
                            Sex = 1,
                            Specialization = 4
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1967, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "physician3@gmail.com",
                            FirstName = "Victor",
                            LastName = "Sullivan",
                            Password = "10/w7o2juYBrGMh32/KbveULW9jk2tejpyUAD+uC6PE=",
                            Role = "Physician",
                            Sex = 0,
                            Specialization = 8
                        });
                });

            modelBuilder.Entity("WebClinicAPI.Models.Users.Receptionist", b =>
                {
                    b.HasBaseType("WebClinicAPI.Models.Users.AppUser");

                    b.HasDiscriminator().HasValue("Receptionist");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1990, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "receptionist1@gmail.com",
                            FirstName = "Rajesh",
                            LastName = "Koothrappali",
                            Password = "10/w7o2juYBrGMh32/KbveULW9jk2tejpyUAD+uC6PE=",
                            Role = "Receptionist",
                            Sex = 0
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1986, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "receptionist2@gmail.com",
                            FirstName = "Penny",
                            LastName = "Hofstadter",
                            Password = "10/w7o2juYBrGMh32/KbveULW9jk2tejpyUAD+uC6PE=",
                            Role = "Receptionist",
                            Sex = 1
                        });
                });

            modelBuilder.Entity("WebClinicAPI.Models.Appointment", b =>
                {
                    b.HasOne("WebClinicAPI.Models.Users.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId");

                    b.HasOne("WebClinicAPI.Models.Users.Physician", "Physician")
                        .WithMany("Appointments")
                        .HasForeignKey("PhysicianId");
                });
#pragma warning restore 612, 618
        }
    }
}
